apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: CustomMachine
metadata:
  name: cc-custommachine
  namespace: default
spec:
  master:
    - hostName: master1
      publicIP: 202.x.x.x
      privateIP: 192.x.x.x
      sshKey:
        apiVersion: v1
        kind: Secret
        name: cluster-secret
  node:
    - hostName: node1
      publicIP: 202.x.x.x
      privateIP: 192.x.x.x
      sshKey:
        apiVersion: v1
        kind: Secret
        name: cluster-secret
