apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kurator-fleet-manager
rules:
  - apiGroups:
      - fleet.kurator.dev
    resources:
      - '*'
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.kurator.dev
    resources:
      - '*'
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kurator-fleet-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kurator-fleet-manager
subjects:
  - kind: ServiceAccount
    name: kurator-fleet-manager
    namespace: {{ .Release.Namespace }}
