{{ if .Values.aws.credentials }}
apiVersion: v1
data:
  credentials: {{ .Values.aws.credentials }}
kind: Secret
metadata:
  name: kurator-aws-bootstrap-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
