apiVersion: v1
kind: Service
metadata:
  name: kurator-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    app.kubernetes.io/name: kurator-cluster-operator
