apiVersion: v1
kind: Service
metadata:
  name: kurator-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    control-plane: kurator-cluster-operator
