baseURL = 'https://kurator.dev/'
languageCode = 'en-us'
title = 'Kurator'

disableKinds = ["taxonomy", "taxonomyTerm"]

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
[languages]
[languages.en]
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.zh]
languageName ="中文"
contentDir = "content/zh"

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
