baseURL = 'https://kurator.dev/'
languageCode = 'en-us'
title = 'Kurator'

disableKinds = ["taxonomy", "taxonomyTerm"]

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
[languages]
[languages.en]
languageName ="English"

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

[params.mermaid]
enable = true

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

## Configuration for goldmark markdown parser: https://gohugo.io/getting-started/configuration-markup#goldmark
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "tango"
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  noClasses = false
  tabWidth = 2
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
# [blackfriday]
# plainIDAnchors = true
# hrefTargetBlank = true
# angledQuotes = false
# latexDashes = true

# Highlighting config
# pygmentsCodeFences = true
# pygmentsUseClasses = false
# # Use the new Chroma Go highlighter in Hugo.
# pygmentsUseClassic = false
# #pygmentsOptions = "linenos=table"
# # See https://help.farbox.com/pygments.html
# pygmentsStyle = "emacs"

[params]
copyright = "The Kurator Authors"

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

[[params.links.user]]
	name ="Kurator GitHub repository"
	url = "https://github.com/kurator-dev/kurator/"
	icon = "fab fa-github"
  desc = "Kurator GitHub"
[[params.links.user]]
	name = "Kurator slack"
	url = "https://join.slack.com/t/kurator-hq/shared_invite/zt-1sowqzfnl-Vu1AhxgAjSr1XnaFoogq0A"
	icon = "fab fa-slack"
  desc = "Kurator on slack"
[[params.links.user]]
	name = "Kurator mailing list"
	url = "https://groups.google.com/g/kurator-dev"
	icon = "fa fa-envelope"
  desc = "Kyverno mailing list"
