baseURL = 'https://kurator.dev/'
languageCode = 'en-us'
title = 'Kurator'

disableKinds = ["taxonomy", "taxonomyTerm"]

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
[languages]
[languages.en]
languageName ="English"

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

[markup.goldmark.renderer]
unsafe = true
